# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='vin',
            name='appelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.Appelation'),
        ),
    ]
