# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 01:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_vin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=5)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('appelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.Appelation')),
            ],
        ),
    ]
