# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0006_auto_20170107_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='appelation',
        ),
        migrations.AddField(
            model_name='commune',
            name='appelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.Appelation'),
        ),
    ]
